# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: fernwood
    binary: fernwood
    main: ./cmd/fernwood
    env:
      - CGO_ENABLED=0
    tags:
      - stdjson
    ldflags:
      - -s -w
      - -X github.com/strand1/fernwood/cmd/fernwood/internal.version={{ .Version }}
      - -X github.com/strand1/fernwood/cmd/fernwood/internal.gitCommit={{ .ShortCommit }}
      - -X github.com/strand1/fernwood/cmd/fernwood/internal.buildTime={{ .Date }}
      - -X github.com/strand1/fernwood/cmd/fernwood/internal.goVersion={{ .Env.GOVERSION }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: "fernwood_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: strand1
    name: fernwood
